---
title: "4.1 Intro to Animal Social Networks"
author: "Dai Shizuka"
date: "7/10/2018"
output: 
  html_document:
    toc: yes
    toc_depth: 3
---

```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(fig.width=6, fig.height=4) 
set.seed(2)
```

Animals interact and associate. These interactions and associations can build up to social relations between individuals in a population. *Social structure* refers to the global description of these social relations (Hinde 1976). Social network analysis can be used as a method to quantify the structure and dynamics of animal societies. There has been an explosion of empirical studies (and review articles) on the topic since the early 2000s.

As mentioned in the [survey of network types](04_networktypes.html), social networks describe the dynamics of social interactions and associations (edges) between individuals (nodes). However, there are potential bananaskins to look out for when constructing social networks. The most important question here (and whenever you are making networks in general) is: ***what are your edges?***

##4.1.1. Constructing networks from interactions



##4.1.2. Constructing networks from associations