---
title: "4. Survey of Networks for Ecologists"
author: "Dai Shizuka"
date: "7/10/2018"
output: 
  html_document:
    toc: yes
    toc_depth: 3
---

--------------

##4. AN ECOLOGIST’S GUIDE TO DIFFERENT NETWORK TYPES

There are dozens of different types of biological networks. I will focus on a few main types of networks here. For each network, it is particularly important to think about how nodes and edges are defined.

We will present three general types of networks that have been of particular interest for ecologists, each with particular challenges. After a brief overview, I highlight a few particular topics for each type of network.


###4.1. Social networks
Social networks describe the dynamics of social interactions and associations (edges) between individuals (nodes). Examples of the types of interactions/associations involved include direct interactions (e.g., aggression, grooming), co-membership in groups such as herds and flocks, or co-use of spatial locations (e.g., roosts, refuges). The analysis of such social networks can be used to understand the structure of societies, the dynamics of social structure across time and space, and the flow of information/disease/etc through these connections.

![Fig1: Example of a social network: Grooming and play networks of pigtail macaques (Macaca nemestrina). Photo by Frank Vincentz via wikimedia, Networks from from Flack et al. (2006).[^1]](https://www.dropbox.com/s/jec9dgm7npwgh1i/ASN_fig1.png?dl=1)

Social network analysis has a long history in fields such as sociology, where it dates back to at least the 1930s. Among ecologists, social networks have been used by primatologists for many decades. However, the study of animal social networks has undeniably exploded in the past decade. This is a field with many review articles (Krause et al. 2007, Wey et al. 2008, Sih et al. 2009, Pinter-Wollman et al. 2014) and books (Croft et al. 2008, Whitehead 2008, Krause et al. 2015) which are recommended for those who are interested in learning more.

Go to a specific tutorial for how to construct social networks [here](04.1_socialnetworks.html)


###4.2 Ecological Networks

In many ecological networks, nodes represent species and edges represents some sort of species interaction. Two prominent examples include food webs and mutualism networks. In food webs, the edges represent trophic interactions. In mutualism networks, the edges may represent interactions such as plant-pollinator relations. In mutualism networks in particular, the network may be *bipartite*: that is, there are two types of nodes (e.g., plants and pollinators), and interactions only occur between two different types of nodes.


![Plant-pollinator network: photo by Sffubs via wikimedia, network from Burkle et al. 2013[^2]](https://www.dropbox.com/s/wzx0xxm4n2yjayt/PlantPollinator.png?dl=1)

The network view of ecology has a long history (e.g., May 1973), and many great reviews/perspective pieces (Montoya et al. 2006; Bascompte & Jordano 2007; Ings et al. 2009) and books (e.g., Pacual & Dunne 2006) now exist. We will not even scratch the surface of the advances in this area over the past couple of decades!




[^1] (https://www.nature.com/articles/nature04326)
[^2] (http://science.sciencemag.org/content/339/6127/1611)