---
title: "Intro to Network Analysis in R"
output: 
  html_document:
    theme: flatly
---

####Hello to my network analysis tutorials. This website is a repositories of tutorials for network analysis that I have used in my course for graduate students. The materials on this page tend to be geared towards ecologists, and *behavioral ecologists* in particular. This simply reflects my own training and research interests. 

####The tutorial materials demonstrate how to use the [R programming environment](https://cran.r-project.org/) to start conducting network analysis (again, primarily the types of networks that ecologists tend to use). Most of the materials utilize the [igraph package for R](http://igraph.org/r/). 

####I will do my best to continue to update the material. However, this is not really an active blog where I will be posting regular updates all the time. If there is something that is amiss in the tutorials, please feel free to send me a note. I will keep my contact info updated in the [about page](about.html).

-----

##Why Network Analysis?

A major challenge in ecologists and evolutionary biology is understanding how levels of biological organization are connected. How do molecules build organisms? How do individual organisms interact, and how does that influence the change in populations across space and time? How are populations of a given species similar or different? What are the roles of species within communities? 

These and other questions involve understanding how the *interactions* or *connections* between components make up a *system*. That is, ***each level of biological organization is more than the sum of its parts***. 

Network theory (and the related fields of graph theory and complexity theory) is an approach to understanding how the processes that govern how elements--e.g., molecules, individuals, and species--connect together to create patterns inherent in the larger system such as an organism, a population, or ecological community. 

Thus, network analysis allow us to ask questions about:

* The processes that build systems
* The architecture of systems
* The roles of individual elements within a system
* The dynamics of flow (e.g., of information, disease, energy, etc.) within a system

... where "Systems" can be anything from social networks of humans & animals, ecological communities, complex traits, connections between populations, gene regulation systems, metabolic systems, etc. etc. --Basically, anything that is more than just a sum of individual elements is a complex system. 


