---
title: "Syllabus"
output: 
  html_document:
    toc: yes
    toc_depth: 2
---

---------

This is the syllabus for the Shizuka Lab Retreat/Workshop on Network Analysis, hosted at School of Biological Sciences, UNL in summer 2018.

##<u>Dates/Location</u>  
* **July 16-20, 2018. Sessions start daily at 9am in Room 401 Manter Hall**  
  
     
##<u>Instructor</u>  
* **Dai Shizuka**
* **Office: 410B Manter Hall**
* **Email: dshizuka2'at'unl.edu** 

    
##<u>Course Website</u>  
####Course materials will be posted at the course blog: [https://dshizuka.github.io/network2018](https://dshizuka.github.io/network2018)####  

    
##<u>Before you start</u>


###1. Install Rstudio

This workshop will use R as the base language for all computer exercises. I have made this site as user-friendly as possible, but it is good for you to have the basics of R under your belt before you embark on these lessons. 


###2. Install Packages

Run this code:
```{r, eval=F}
install.packages(c("igraph", "bipartite", "asnipe", "assortnet", "ggplot2", "ggmap", "rnetcarto", "ecodist", "igraphdata", "statnet", "RColorBrewer"))
```


###3. Download data

Go to [this link](https://dshizuka.github.io/network2018/NetworkWorkshop_SampleData.zip) and download the compressed data files. Save the file into a folder that you can remember. This will allow us to run some of the examples even if internet access fails.